name: Deploy Worker
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ WH1OJMU2EOm_08YFBnhmK55577ovoqkwCuwc8KRK }}
          accountId: ${{ 5c39c0589a4d16357f807e75bfc50bbc }}
