name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  # 初始无依赖任务（必需）
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  test:
    runs-on: ubuntu-latest
    needs: init  # 声明依赖
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [init, test]
    steps:
    - uses: actions/checkout@v4
    - name: Install Wrangler Locally
      run: npm install wrangler --save-dev
    - name: Verify Wrangler Installation
      run: npx wrangler --version
    - name: Deploy with Wrangler
      run: npx wrangler publish
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
