name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  # 初始无依赖任务（必需）
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  test:
    runs-on: ubuntu-latest
    needs: init  # 声明依赖
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test

  deploy:
  runs-on: ubuntu-latest
  needs: [init, test]  # Multiple dependencies
  steps:
    - uses: actions/checkout@v4
    - name: Install Wrangler
      run: npm install -g wrangler
    - name: Deploy with Wrangler
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
